import type { en } from "./en";

export const he: typeof en = {
  nav: {
    experience: "ניסיון תעסוקתי",
    skills: "מטריצת כישורים",
    education: "הכשרות והסמכה",
    projects: "פרויקט אוטומציה",
    contact: "צור קשר",
    langToggle: "English",
    themeLabel: "ערכת עיצוב",
    themes: { ocean: "אוקיינוס", matrix: "מטריקס", neon: "ניאון", light: "בהיר" },
  },
  hero: {
    badge: "מוכנות לתפקידי SDET ואוטומציה",
    title: "דוד כהן",
    subtitle:
      "מהנדס בדיקות תוכנה המתמחה במערכות פיננסיות קריטיות ואימות תהליכים מורכבים מקצה לקצה. מיישם מתודולוגיות בדיקה מתקדמות ואוטומציה בסביבות מבוזרות.",
    ctaEmail: "✉️ שלח מייל",
    ctaLinkedin: "🔗 פרופיל לינקדאין",
    phone: "054-9495729",
    terminalTitle: "דוד@תחנת-QA: ~/תיק-עבודות",
    terminalFooter: "בילד: עובר · לינט: נקי · נגישות: AA",
    terminal: [
      "$ run e2e-suite --env=core-banking",
      "✓ 128 מקרי בדיקה בוצעו",
      "✓ 0 באגים קריטיים דלפו",
      "→ סטטוס: READY_FOR_AUTOMATION",
    ],
  },
  exp: {
    eyebrow: "01 · ניסיון",
    title: "ניסיון תעסוקתי",
    company: "Qualitest (פרויקט בנק הפועלים)",
    role: "בודק תוכנה ידני",
    date: "2025 – היום",
    bullets: [
      { text: "ביצוע בדיקות פונקציונליות ומקצה לקצה בסביבת Agile (Scrum) על מערכות ליבה בנקאיות קריטיות.", tags: ["Agile", "E2E"] },
      { text: "כתיבה, עדכון והרצה של תסריטי בדיקה מקיפים ומטריצות בדיקה באמצעות תוסף Xray.", tags: ["Xray"] },
      { text: "ניהול, תיעוד ומעקב מקיף אחר מחזור חיי הבאגים ב-Jira בשיתוף צוותי פיתוח ומוצר עד לסגירה מלאה.", tags: ["Jira"] },
      { text: "בדיקות API ממוקדות באמצעות Postman (REST), כולל אימות קודי סטטוס, מבנה הנתונים (Payload) ו-Schemas.", tags: ["API", "Postman"] },
      { text: "ביצוע בדיקות אינטגרציה מורכבות (SIT) בסביבות מבוזרות המשלבות מערכות Mainframe ורכיבי ESB.", tags: ["SIT", "Mainframe", "ESB"] },
      { text: "תחקור, ניתוח והפקת דוחות לוגים לאיתור ובידוד תקלות קצה מורכבות בעזרת מערכת Splunk.", tags: ["Splunk"] },
      { text: "שליפת נתונים, הצלבות מידע וביצוע וולידציות מורכבות ישירות מול בסיסי נתונים ב-SQL (Teradata).", tags: ["SQL", "Teradata"] },
    ],
  },
  skills: {
    eyebrow: "02 · כישורים",
    title: "ארגז כלים ומיומנויות מקצועיות",
    cats: [
      { name: "מתודולוגיות בדיקה", items: ["תכנון STP / STD / STR", "בדיקות רגרסיה (Regression)", "אימות ממשקי API", "בדיקות אינטגרציה ו-E2E"] },
      { name: "כלים ומערכות", items: ["מערכות Jira & Xray", "כלי הבדיקה Postman", "מערכת לוגים Splunk", "Chrome DevTools Shell"] },
      { name: "שפות תכנות ונתונים", items: ["פיתוח אוטומציה ב-Java", "שימוש ב-Selenium", "שאילתות SQL מורכבות", "בסיסי נתונים Teradata"] },
    ],
  },
  edu: {
    eyebrow: "03 · הכשרות",
    title: "השכלה והכשרות מקצועיות",
    college: "קורס QA ואוטומציה, המכללה לאוטומציה (גל מטלון)",
    date: "2023–2024",
    bullets: [
      "כתיבה ובנייה מובנית של מסמכי בדיקות מקיפים (STP, STD, STR).",
      "ניהול מחזורי בדיקות מעשיים תוך שימוש במערכות TestRail וסביבות Jira ארגוניות.",
      "ביצוע בדיקות פונקציונליות ורספונסיביות מתקדמות עבור אפליקציות Web ופלטפורמות Mobile.",
      "פיתוח שאילתות מורכבות בבסיסי נתונים יחסיים (SQL) עד רמת שימוש ב-JOINs מורכבים.",
    ],
    pipeline: {
      title: "פייפליין אוטומציה",
      badge: "חי באוויר",
      desc: "תיק עבודות אוטומציה ציבורי בגיטהאב — תשתית בדיקות UI ב-Java + Selenium עם ארכיטקטורה מודולרית, חיה ומתפתחת.",
      cta: "פתיחת הריפוזיטורי",
    },
  },
  projects: {
    eyebrow: "04 · אוטומציה",
    title: "תשתית בדיקות אוטומטיות — Java & Selenium",
    badge: "קוד מקור מאומת",
    sub: "פרויקט האוטומציה החי שלי — קוד אמיתי, ציבורי בגיטהאב.",
    repoName: "qa-automation-portfolio",
    repoDesc:
      "פיתוח ארכיטקטורת בדיקות אוטומטיות מובנית (UI Testing Framework) המיועדת למערכות Enterprise. התשתית כוללת קלאסים מודולריים להפעלת מנהלי דפדפנים, ניהול מנגנוני סינכרון ואימות תהליכי התחברות וחיפוש מורכבים.",
    cta: "ניתוח ארכיטקטורת קוד ב-GitHub",
    tags: ["Java SE", "Selenium WebDriver", "OOP Architecture", "Regression Triggers"],
    statLabel: "סטטוס",
    statValue: "בפיתוח פעיל",
  },
  jira: {
    eyebrow: "05 · טלמטריה",
    title: "סימולציית תחקור תקלה ודיווח ב-Jira",
    ticketLabel: "כרטיס תקלה לדוגמה (Jira Template)",
    ticketId: "DB-409",
    priority: "P1_BLOCKER",
    summaryLabel: "תקציר התקלה",
    summary: "CRITICAL: שגיאת פסק זמן (Timeout) בגשר ה-API בין מערכות ה-Web ל-Mainframe",
    envLabel: "סביבת יעד",
    env: "סביבת SIT / שער תקשורת פיננסי",
    reproLabel: "צעדים לשחזור",
    repro:
      "1. שליחת עומס תנועות מדומה לקצה ה-REST API באמצעות Postman.\n2. תחקור ויירוט לוגים בזמן אמת בשרתי Splunk.\n3. אימות סטטוס הרשומות בטבלאות בסיס הנתונים ב-Teradata.",
    expectedLabel: "תוצאה צפויה",
    expected: "קבלת קוד סטטוס HTTP 200 OK בתוך מגבלת זמן של עד 150 מילישניות.",
    actualLabel: "תוצאה בפועל",
    actual: "שגיאת HTTP 504 Gateway Timeout; זוהתה נעילת טבלאות (Database Lock) במהלך הסנכרון.",
  },
  contact: {
    eyebrow: "06 · צור קשר",
    title: "צרו קשר",
    sub: "מגייסים לתפקיד QA או אוטומציה? בואו נדבר.",
    phoneLabel: "טלפון",
    emailLabel: "אימייל",
    linkedinLabel: "לינקדאין",
    linkedinCta: "פתיחת פרופיל",
  },
  footer: {
    tagline: "מהנדס בדיקות • בנקאות ליבה • מוכן לאוטומציה",
    rights: "כל הזכויות שמורות.",
  },
};
